### ISSUE TITLE
Add a decoder for morse code

### ISSUE THREAD

**Issue by Veershah26** [nimit2801/MorseCodeMessenger#2]
Try making a decoder which can also hear to audio and convert it to text.

**Comment by nimit2801** [comment]
Hey that was a great idea. :0 I'll reopen the issue it adds up a great feature into the pyscript 
Feel free to submit a PR 👍

**Comment by slaterslater** [comment]
Did you want to decode a string of dots and dashes or a wav file of dits and dahs?

**Comment by nimit2801** [comment]
wave file to dots and dashes @slaterslater

**Comment by slaterslater** [comment]
Ok. I think I can do that. Assign this to me?
